---
abstract: 'Relational Database Persistence for Perl Objects'
author:
  - 'Jim Schueler <jim@tqis.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NoSQL-PL2SQL
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: 1.37
  DBI: 1.57
  XML::Parser::Nodes: 0.04
version: 1.10
